### ISSUE TITLE
expose hooks for tokens, media queries, and other config values

### ISSUE THREAD

**Issue by alidcast** [gluestack/gluestack-style#127]
Sometimes it's useful to set media queries or dynamic states as props, otherwise it's useful to do it via a hook.

It would be great to access the config values, such as media query or token value, via a hook.

**Comment by ankit-tailor** [comment]
Hey @alidcast, Thanks for the suggestions. We will have a discussion about it and keep you updated.

**Comment by ankit-tailor** [comment]
Hey @alidcast, We have added hooks `useToken`, `useBreakpointValue` and `useColorMode`.
