### ISSUE TITLE
props with media queries not merged correctly

### ISSUE THREAD

**Issue by alidcast** [gluestack/gluestack-style#157]
Issue 1: when css styles are included, `props` values passed to a component are `undefined`.

So below, `media` is `undefined` when css styles are included (bg, width, height).

```
const PassedProps = ({ media, ...props}) => console.log(media) as any || (
	<View {...props}>
		<Text>{media}</Text>
	</View>
)

const Example = styled(PassedProps, {
        // example css styles, comment out to see difference
	backgroundColor: 'blue',
	width: 100,
	height: 200,
        // demo props
	props: {
		media: 'small',
	},
	'@lg': {
		backgroundColor: 'pink',
		props: {
			media: 'large'
		}
	}
})
```

Issue 2: When no css styles are included, the media query is not checked.

So below, even in a mobile screen, the prop `large` is returned rather than `small`.

```
// Same `PassedProps` as above
const Example = styled(PassedProps, {
	props: {
	  media: 'small',
	},
	'@lg': {
		props: {
			media: 'large'
		}
	}
})
```

Issue 3: props with media queries are not merged.

Below, `variant` isn't included if `@lg` props is returned.

```
const Example = styled(PassedProps, {
	props: {
	  media: 'small',
           variant: 'primary'
	},
	'@lg': {
		props: {
		   media: 'large'
		}
	}
})
```

Issue 4 (optional): Props nested under a media query do not update when the window dimensions change.
related to commentary in #127

**Comment by AshwiniKumar007** [comment]
Hey @alidcast ,

Thanks for reporting. We will look into this

**Comment by ankit-tailor** [comment]
Hey @alidcast, Passing props inside media queries will not work because media queries are injected as CSS on the web. Also, it is not recommended to use passing props like this. We may want to expose a media query hook for this use case, which is already in our roadmap.

**Comment by ankit-tailor** [comment]
Hey @alidcast, Thanks for the suggestions. we will add warnings for more clarification and mention this in the documentation as well.

**Comment by ankit-tailor** [comment]
Hey @alidcast, Closing the issue as this is not the use case of passing props. You can track issue #127 for core hooks.
