### ISSUE TITLE
Property mapping `sizes`

### ISSUE THREAD

**Issue by Christopher2K** [gluestack/gluestack-style#181]
Hi team!

I noticed that the `sizes` property mapping is disabled atm. Any reasons for that? How can I help?

https://github.com/gluestack/dank-style/blob/0d94e81b0ebc298d91032f0e6a8e725fad4dbd79/packages/react/src/propertyTokenMap.ts#L13

**Comment by ankit-tailor** [comment]
Hey @Christopher2K, The issue is fixed. Please update to the latest version.
