### ISSUE TITLE
text style not properly flushed with ssr

### ISSUE THREAD

**Issue by aleedmanath** [gluestack/gluestack-style#294]
Styles set on a text element only show up on client hydration, leading to SSR flicker when the state hydrates.

Regular `View` styles work fine, so this is specific to Text styles.

Example components:
```

// will hydrate same
const Row = styled(View, {
	flexDirection: "row"
})

// will hydrate differently
const Heading = styled(
  Text,
  {
    fontWeight: "900",
    fontStyle: "normal"
  }
)
```

**Comment by surajahmed** [comment]
@aleedmanath Thanks for reporting. This issue is resolved in version `0.1.29`. Please let us know if this issue persists.
