### ISSUE TITLE
SSR hydration fails due to miss match

### ISSUE THREAD

**Issue by Evanion** [gluestack/gluestack-style#304]
Added Gluestack-ui to a clean next.js project using app router.
Created a custom styled component called `CenteredWrapper` that relies on `@gluestack-styled/react`

At first when the page renders, the css is applied correctly, but when the client side hydration is performed, there is a miss match, and the correct styling is removed.

Not sure if this should be put here, or in the gluestack-ui board, but since it seems to originate in the styled package, I posted it here.

Reprod repo: https://github.com/Evanion/reprod-gluestack

* clone
* yarn install
* `nx serve frontend`
* navigate to `http://localhost:4200/sign-in`

At first the text will appear centered on the page, but once the hydration is performed, the text will move to the top left corner of the screeen.

code is located in `<repo root>/apps/frontend/app/sign-in/page.tsx`

**Comment by surajahmed** [comment]
@Evanion Thanks for reporting. We'll look into this.
