### ISSUE TITLE
styled() docs have type

### ISSUE THREAD

**Issue by jmurp7385** [gluestack/gluestack-style#313]
On the webpage for the [docs](https://style.gluestack.io/docs/getting-started/styled) about the `styled()` function, there are several typos that should be fixed.
The page refers to "extenedBaseConfig" instead of "extendedBaseConfig"

![image](https://github.com/gluestack/gluestack-style/assets/19793399/a8e4a54f-0ef8-49dd-b5e6-a8f1ae891cbe)
![image](https://github.com/gluestack/gluestack-style/assets/19793399/c0ae1e0e-f5a2-4cda-85e4-79c2c5b20a1c)

**Comment by AshwiniKumar007** [comment]
Thanks for reporting this @jmurp7385 . We will fix this

**Comment by ankit-tailor** [comment]
Hey @jmurp7385, The issue is fixed.
