### ISSUE TITLE
Using Gluestack-style along with Gluestack-UI?

### ISSUE THREAD

**Issue by Seanmclem** [gluestack/gluestack-style#384]
### Discussed in https://github.com/gluestack/gluestack-style/discussions/383

<div type='discussions-op-text'>

<sup>Originally posted by **Seanmclem** September  2, 2023</sup>
So I was using Gluestack style/ui about a month ago. After a recent update it is totally different now, so I refactored my project over to just using the newer Gluestack-ui. 

If I want to be able to use custom styes or new custom components made with Gluestack-style, along side usage of gluestack-UI, what would that look like? Which `StyledProvider` vs `GluestackUIProvider` would I use? One or both? what about the theme-config? Would there be 2, now?

For the [ui-docs](https://ui.gluestack.io/docs/guides/install-expo) and the [style-docs](https://style.gluestack.io/docs/getting-started/install-expo) for installation. Neither seem to mention each other. What would that even look like?</div>

**Comment by ankit-tailor** [comment]
Hey @Seanmclem, You don't need to use `StyledProvider` as you are already using `GluestackUIProvider`.  `GluestackUIProvider` uses `StyledProvider` internally.  So you can straightaway create your own components which will use the same config as gluestack-ui.

**Comment by Seanmclem** [comment]
Thanks, I'll try that and come back if I have any questions or close it.

**Comment by Viraj-10** [comment]
Hey @Seanmclem, Closing this issue. Feel free to open a discussion or create a issue if you find one.
