### ISSUE TITLE
[OPTIMIZATIONS] some errors when install @gluestack-style/babel-plugin-styled-resolver

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-style#459]
https://gluestack.io/ui/docs/production-optimizations/babel-plugin
```
npm i @gluestack-style/babel-plugin-styled-resolver
```
![截屏2023-10-05 14 32 01](https://github.com/gluestack/gluestack-style/assets/16587763/1f368ec2-1654-42db-9cca-cd23cdd4a8c8)

**Comment by ankit-tailor** [comment]
Hey @BooYeu, You can do `npm i @gluestack-style/babel-plugin-styled-resolver --legacy-peer-deps`.
