### ISSUE TITLE
Element type is invalid: Check the render method of 'StyledComponent'. Problem with animation.

### ISSUE THREAD

**Issue by steve-rodri** [gluestack/gluestack-style#462]
![Simulator Screenshot - iPhone SE (3rd generation) - 2023-10-05 at 11 43 42](https://github.com/gluestack/gluestack-style/assets/24379257/eb4e54a2-4c89-4689-85d7-ce7f545f1b3d)

### To Reproduce:

Create a new project with:

```
npm create gluestack
```

choose "Mobile App" - Expo

you could name it "animation-test"

```
cd animation-test
```

Make sure to have the animation plugin installed:

```
npm i @gluestack-style/animation-plugin
```

Remove App.tsx and replace with the following:

```
import { AnimationResolver } from "@gluestack-style/animation-plugin";
import { createStyled } from "@gluestack-style/react";
import { GluestackUIProvider } from "@gluestack-ui/themed";
import { Motion } from "@legendapp/motion";

const styled = createStyled([new AnimationResolver()]);

export const StyledMotionView = styled(Motion.View, {});

export default function App() {
  return (
    <GluestackUIProvider>
      <StyledMotionView />
    </GluestackUIProvider>
  );
}
```

Start the app and observe the error:

```
nom start
```

**Comment by ankit-tailor** [comment]
Hey @steve-rodri, We have changed the API for animations. You can checkout [here](https://gluestack.io/style/docs/plugins/animation-plugin).
