### ISSUE TITLE
importing @gluestack-style/config crash with styled-resolver

### ISSUE THREAD

**Issue by fnky** [gluestack/gluestack-style#517]
When using the `@gluestack-style/babel-plugin-styled-resolver` babel plugin, importing `@gluestack-style/config` results in the following error to be thrown:

```
node_modules/@gluestack-ui/config/build/gluestack-ui.config.js: /Users/chris/Development/Personal/Expo/gluestack-babel-bug-repro/node_modules/@gluestack-ui/config/build/gluestack-ui.config.js: Cannot read properties of undefined (reading 'forEach')
```

You can find a minimal reproduction of this [here](https://github.com/fnky/gluestack-babel-bug-repro).

Clone the repo and run `yarn start --clear` (to ensure cache clearance) and start the project on iOS or Android.

Removing the babel plugin resolves the issue.

Tested on Expo 48 and 49. Not tested with bare React Native.

Also tested with and without setting `GLUESTACK_STYLE_TARGET=native` environment variable.

**Comment by ankit-tailor** [comment]
Hey @fnky, Thanks for reporting the issue. We'll look into it.

**Comment by Gluant101** [comment]
Hi @fnky, we are going to pick this up in the next few sprints. There are pending tasks that are prioritised higher in our tracker. Hope you understand 🙂

**Comment by ankit-tailor** [comment]
Hey @fnky, Please try the latest version of `@gluestack-style/babel-plugin-styled-resolver`.
