### ISSUE TITLE
Adding babel plugin to next-head-starter-kit fails

### ISSUE THREAD

**Issue by jono-allen** [gluestack/gluestack-style#532]
When installing `@gluestack-style/babel-plugin-styled-resolver@^1.0.1` on the [next-head-starter-kit ](https://github.com/gluestack/next-head-starter-kit) it fails with a reference error
```
ReferenceError: unknown node of type undefined with constructor "Object"
```

Example 
https://github.com/typed-development/gluestack-memory/tree/babel-plugin

Running command
```
GLUESTACK_STYLE_TARGET=web  yarn build
```

**Comment by surajahmed** [comment]
@jono-allen Thanks for reporting this. We'll look into this.

**Comment by Gluant101** [comment]
Hi @jono-allen, we are going to pick this up in the next few sprints. There are pending tasks that are prioritised higher in our tracker. Hope you understand 🙂

**Comment by surajahmed** [comment]
@jono-allen This issue is resolved in the latest version of  `@gluestack-style/babel-plugin-styled-resolver` and `@gluestack-style/react`.
Thanks for your patience.
