### ISSUE TITLE
fontSize cannot be a string in TypeScript, cannot use tokens

### ISSUE THREAD

**Issue by gausie** [gluestack/gluestack-style#80]
Providing a token to a component's "fontSize" is marked as an error in TypeScript

**Comment by ankit-tailor** [comment]
Hey @gausie, Thanks for reporting the issue. We will look into it.

**Comment by ankit-tailor** [comment]
Hey @Christopher2K, This issue has been fixed. Closing it for now. Feel free to open it if you still face the issue.
